version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo "Logging in to AWS CodeArtifact..."
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 738408429981 --region us-east-1 --query authorizationToken --output text`
      - echo "Auth token length: ${#CODEARTIFACT_AUTH_TOKEN}"  # optional debug

  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean install -s settings.xml   # install already packages the .war

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - target/*.war
  discard-paths: no
 